### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by NeoCro44** [shyim/op-gg-remove-ads#1]
It has been working very nice untill last op.gg update. now block adds but not all

**Comment by shyim** [comment]
I will look later. I saw it also yesterday 😓

**Comment by NeoCro44** [comment]
Thank you

**Comment by shyim** [comment]
fixed with https://github.com/shyim/op-gg-remove-ads/releases/tag/0.1.1

**Comment by shyim** [comment]
you should reinstall first op.gg
