### ISSUE TITLE
not working after update

### ISSUE THREAD

**Issue by gutaewoo** [shyim/op-gg-remove-ads#10]
not working after opgg update ...

op-gg-remove-ads update plz

**Comment by MidKnightXI** [comment]
The directory that was specified in the code where the ads were(`assets/react`) got removed and got replaced by a `main` directory containing `main.js` and `preload.js`.

Im still looking into it to find where the ad links are located with that new update but I guess we will have to work with that `assets/main` directory.

**Comment by shyim** [comment]
@MidKnightXI if your project works, I can archive this here :). makes no sense to have 2 projects doing same

**Comment by MidKnightXI** [comment]
I'm having literally the same problem atm I was wondering if you found a solution to it

**Comment by MidKnightXI** [comment]
@shyim I'm currently working on the same issue on my side.

If you want to archive your repo maybe link mine so people aren't lost when they see that you archived yours.

And don't hesitate to come help sometime if you have some spare time, it's always appreciated. 🫡

**Comment by MidKnightXI** [comment]
> @MidKnightXI if your project works, I can archive this here :). makes no sense to have 2 projects doing same

I can't work on the project atm because I don't have access to a windows machine(I'm on macOS) and the update is still not released on this platform.

My only way of working on it is through a VM and it's just sucking my laptop's battery and the performances are horrible when I'm building my project on it ...

So until OPGG release its update on macOS I think it's better if you can try to find a fix if you have time to.

**Comment by shyim** [comment]
I will have a look and fix it. Have vacatation this week and bought the league pass :D

**Comment by MidKnightXI** [comment]
Thank you so much man, have some nice vacation 🙏🏻

**Comment by shyim** [comment]
I would say try out https://github.com/shyim/op-gg-remove-ads/releases/tag/0.2.2

![image](https://user-images.githubusercontent.com/6224096/227905714-98c637da-f82d-4038-a054-c9ab180bf90d.png)

The ad placeholders are still there, but they are not displayed. OP.GG is so evil to read chrome cookies 🙈

**Comment by MidKnightXI** [comment]
I'll add it right away to release a working build for windows on my side

**Comment by MidKnightXI** [comment]
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/35759490/227921383-e4fa6258-4711-493a-921e-c0e6e633930f.png">

Not working on my side with 0.2.2

**Comment by shyim** [comment]
I will take a look again. I guess i figured out why I have never ads. It's my local Adguard Home 🤣

**Comment by shyim** [comment]
With the last tagged version it really works. Now I have to take a bath to get rid of this dirt on me.

Feel free to use my Cloudflare Worker too.

For the context:

They remove their complete frontend code and host it now on their own cdn. So we can't remove it locally anymore. First ideas was to add https://github.com/ghostery/adblocker/tree/master/packages/adblocker-electron-example but it's really really instable to add this to the existing main.js

So I set up a own Cloudflare Worker which proxies their CDN and replaces it there
