### ISSUE TITLE
Ad Blocker Not Working in OP.GG Version 1.1.21

### ISSUE THREAD

**Issue by BVLLISTA** [shyim/op-gg-remove-ads#11]
Describe the bug
The ad blocking feature is not working in OP.GG app version 1.1.21 

To Reproduce
Install the latest version of OP.GG
Run op-gg-remove-ads-win.exe
Open OP.GG after successful patch

Expected behavior
The ads will be removed from the app after successful patch, until a new OP.GG update releases.

Screenshots
![image](https://user-images.githubusercontent.com/107594745/233688429-e312a93f-012c-4498-9900-8ad063b17c93.png)

OS: Windows
Version: 11
OP.GG App Version: V.1.1.21

**Comment by shyim** [comment]
I will look tomorrow

**Comment by shyim** [comment]
Is fixed with https://github.com/shyim/op-gg-remove-ads/releases/tag/0.2.4

I have the feeling OP.GG devs are trying to break this by purpose.  No dev ever would base64 encode their own URLs and do an redirect to their own site 😂 

```
var r=function(){8!==location.href.indexOf(atob("YXBwLmxhYnMuc3lkbmV5"))&&8!==location.href.indexOf(atob("b3BnZy1kZXNrdG9wLWRhdGEuYWthbWFpemVkLm5ldA=="))&&7!==location.href.indexOf(atob("bG9jYWxob3N0OjQwMDA="))&&(location.href="https://app.labs.sydney/app/prod/1.1.21/index.html")}
```
