### ISSUE TITLE
Windows Exe flagged as Win64:MalwareX-Gen

### ISSUE THREAD

**Issue by Arcegis** [shyim/op-gg-remove-ads#15]
![image](https://github.com/shyim/op-gg-remove-ads/assets/8590074/4813f80a-339e-49eb-af48-b478c49a1432)

Flagged as malware by Avast Premium Security.

**Comment by MidKnightXI** [comment]
You can run it yourself on your computer if you don't trust the exe.

There are nothing malicious in the code, you can close the issue 👍🏻
