### ISSUE TITLE
Once executed, app keeps trying to open but nothing happens.

### ISSUE THREAD

**Issue by ignaaaam** [shyim/op-gg-remove-ads#2]
Hello brother, executed the .exe (with the file on opgg folder) & with administrative rights, but once all finishes the opgg app just tries to open but nothing happens, it just stay showing the logo but it doesnt start.

Here is how it looks. 
![opggads](https://user-images.githubusercontent.com/39315431/164951163-03650f1b-6d4a-403b-9750-3ab7f7170a4a.png)
.

**Comment by shyim** [comment]
You can kill it with the task manager and open it with the normal shortcut.
I have no glue why its not working anymore in the new releases https://github.com/shyim/op-gg-remove-ads/blob/main/index.js#L55

**Comment by ignaaaam** [comment]
> You can kill it with the task manager and open it with the normal shortcut. I have no glue why its not working anymore in the new releases https://github.com/shyim/op-gg-remove-ads/blob/main/index.js#L55

That's what I did, but if I kill the process and open the app again. It just updates and shows ads again. I'm not an expert on JS yet but if you want I could try to help you or maybe send you more details about it that could help you solve that. Thanks for your repo anyways great work! 👍

**Comment by shyim** [comment]
Does the update always happen after running this tool?

**Comment by ignaaaam** [comment]
> Does the update always happen after running this tool?

Yeah, if I run the tool it gets stuck, if I close the app via task manager and run opgg again it updates and it appears with ads.

**Comment by Davidson-Mike** [comment]
Confirmed - same issue here with OP.GG client 1.0.26. 

Running the patcher works fine, no issues, but when OP.GG re-runs then it gets stuck on that loading page. After ending the process in task manager, and running it again, the client opens for the first time since patching but still has ads.

**Comment by shyim** [comment]
Can you try https://github.com/shyim/op-gg-remove-ads/releases/download/0.1.3/op-gg-remove-ads.exe ?

**Comment by Davidson-Mike** [comment]
> Can you try https://github.com/shyim/op-gg-remove-ads/releases/download/0.1.3/op-gg-remove-ads.exe ?

Thank you for the response on this.

The newest build release, 0.1.3, unfortunately still isn't working on my end.

I run the solution, it completes the patching (no errors/issues). OP.GG no longer restarts on its own, so I start it from the shortcut.

Unfortunately despite all this - ads still exist in the client. See the attached screenshot.

![image](https://user-images.githubusercontent.com/66186881/166319145-0966cb27-d126-4107-b4c6-eee6205022de.png)

I did go ahead and confirm that the patcher is editing the same install folder as I am launching the app from - it is - I only have the one OP.GG installation.

If there's anything else I can share with you to help you debug this issue please let me know.

Edit: I have attempted both running as admin as well as not - same results.

**Comment by Davidson-Mike** [comment]
Quick update - I have prevented `app.asar` from being changed after patching, but the client still shows ads per the above screenshot. `app.asar` is not being updated again after being patched.

**Comment by Abdullah-A4** [comment]
is there a fix to this yet? I am having the same issue.

**Comment by shyim** [comment]
I cannot reproduce that 🙈

**Comment by shyim** [comment]
Can you close OP.GG process in Task manager and run it in cmd with 
```
%LOCALAPPDATA%\Programs\OP.GG\OP.GG.exe
```

It should output things like
```
Checking for update
OverlayMain::addWindow
create share mem:5120,1440
sendChangVisible  4,0
(node:10692) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification
```
which maybe helps

**Comment by atmanli** [comment]
> Can you try https://github.com/shyim/op-gg-remove-ads/releases/download/0.1.3/op-gg-remove-ads.exe ?

I tried it and it got stuck again, but this time, after terminating the process via task manager and then restarting the app, the ads are gone.

**Comment by shyim** [comment]
nice. The OP.GG app is such a bloatware idk it hangs sometimes 😂

**Comment by Dothemright** [comment]
> Can you close OP.GG process in Task manager and run it in cmd with
> 
> ```
> %LOCALAPPDATA%\Programs\OP.GG\OP.GG.exe
> ```
> 
> It should output things like
> 
> ```
> Checking for update
> OverlayMain::addWindow
> create share mem:5120,1440
> sendChangVisible  4,0
> (node:10692) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification
> ```
> 
> which maybe helps

Checking for update
OverlayMain::addWindow
create share mem:1920,1080
sendChangVisible  4,0
(node:26296) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `OP.GG --trace-warnings ...` to show where the warning was created)
Error occurred in handler for 'current-summoner': No handler registered for 'current-summoner'
Update for version 1.0.28 is not available (latest version: 1.0.28, downgrade is disallowed).
update-not-available
Error occurred in handler for 'current-summoner': No handler registered for 'current-summoner'
Error occurred in handler for 'current-summoner': No handler registered for 'current-summoner'
(node:26296) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 did-stop-loading listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(node:26296) electron: Failed to load URL: chrome://version/ with error: ERR_INVALID_URL
(node:26296) electron: Failed to load URL: chrome://version/ with error: ERR_INVALID_URL




I got this by following this instruction....and tried that 0.1.3 ads.exe.  still not working..

**Comment by Dothemright** [comment]
Also my pc is in chinese. but opgg client is in english. i hope that helps you to indicate the issue.

**Comment by shyim** [comment]
I reworked the entire blocking ads. Reinstall OP.GG normal and run the newest version
