### ISSUE TITLE
Can you support Mac?

### ISSUE THREAD

**Issue by ipiiia** [shyim/op-gg-remove-ads#3]
please

**Comment by shyim** [comment]
Hey,

download the macos file from release and open it with right click in finder
https://github.com/shyim/op-gg-remove-ads/releases/tag/0.1.4

**Comment by ipiiia** [comment]
Oh Thank you🥰

**Comment by ipiiia** [comment]
> Hey,
> 
> download the macos file from release and open it with right click in finder https://github.com/shyim/op-gg-remove-ads/releases/tag/0.1.4

I downloaded it, but it doesn't seem to run because there are no filename extension(.dmg, .app,,etc)😭

**Comment by shyim** [comment]
you don't need anyone. just right click open 🤔

**Comment by ipiiia** [comment]
> you don't need anyone. just right click open 🤔

Hmmm.. when I run it, it opens with text editor, and there is an error
`
The document “op-gg-remove-ads-macos” could not be opened. Text encoding Unicode (UTF-8) isn’t applicable.
The file may have been saved using a different text encoding, or it may not be a text file.
`
