### ISSUE TITLE
macOS

### ISSUE THREAD

**Issue by ipiiia** [shyim/op-gg-remove-ads#4]
right click -> open
but It's not an executable file, how did you execute it?..

**Comment by shyim** [comment]
Can you open a Terminal and Write `./` and drag and drop the file into the terminal and press enter?

**Comment by ipiiia** [comment]
> Can you open a Terminal and Write `./` and drag and drop the file into the terminal and press enter?

Yes sir, I've typed it. but it doesn't work..

```
PC@MacBook-Pro ~ % .//Users/PC/Downloads/op-gg-remove-ads-macos  
zsh: no such file or directory: .//Users/PC/Downloads/op-gg-remove-ads-macos
```

**Comment by ipiiia** [comment]
> Can you just type `/Users/PC/Downloads/op-gg-remove-ads-macos` ?

Of course it doesn't work either.

**Comment by Donderda** [comment]
Did you try 
`chmod +x /Users/PC/Downloads/op-gg-remove-ads-macos`
for making it executable?
