### ISSUE TITLE
New ad window cannot be removed!

### ISSUE THREAD

**Issue by noahye24** [shyim/op-gg-remove-ads#8]
V.1.0.51 will pop up an ad window randomly, which cannot be blocked!
The other 2 ad windows are still blocked!
![image](https://user-images.githubusercontent.com/38360170/202354905-cfe5b4e2-cb69-4e36-89ca-cbc9cd900101.png)

Thank you!

**Comment by shyim** [comment]
See https://github.com/shyim/op-gg-remove-ads/releases/tag/0.2.1

**Comment by noahye24** [comment]
Thank you!
